language: csharp
sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 1.0.0-preview2-003121
solution: ./DiscordRestApiLib/DiscordRestApiLib.sln
